version: '3.7'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env

    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
 

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
  

volumes:
  postgres_data:

